-- FONKON route decision report operating model V2
-- Adds model governance, segment-level full-chain data, draft/review/publish,
-- demo isolation, unique-view counting, access-code throttling and audit events.

alter table public.route_reports drop constraint if exists route_reports_status_check;
alter table public.route_reports alter column status set default 'draft';
alter table public.route_reports
  add constraint route_reports_status_check
  check (status in ('draft','pending_review','published','revoked','expired'));

alter table public.route_reports
  add column if not exists model_version text not null default 'FONKON-RM-1-LEGACY',
  add column if not exists is_demo boolean not null default false,
  add column if not exists submitted_at timestamptz,
  add column if not exists approved_at timestamptz,
  add column if not exists published_at timestamptz,
  add column if not exists approved_by uuid references public.profiles(id) on delete set null,
  add column if not exists snapshot_hash text,
  add column if not exists unique_view_count bigint not null default 0 check (unique_view_count >= 0),
  add column if not exists failed_code_attempts integer not null default 0 check (failed_code_attempts >= 0),
  add column if not exists locked_until timestamptz,
  add column if not exists revision integer not null default 1 check (revision >= 1),
  add column if not exists review_notes text;

update public.route_reports
set published_at = coalesce(published_at, created_at)
where status = 'published' and published_at is null;

create table if not exists public.route_model_versions (
  code text primary key,
  label text not null,
  status text not null default 'draft' check (status in ('draft','active','retired')),
  active boolean not null default false,
  config jsonb not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  check (jsonb_typeof(config) = 'object')
);

create unique index if not exists route_model_versions_one_active_idx
  on public.route_model_versions(active) where active;

insert into public.route_model_versions(code,label,status,active,config,activated_at)
values (
  'FONKON-RM-2.0.0',
  '全链路同口径决策模型 2.0',
  'active',
  true,
  jsonb_build_object(
    'method','deterministic_materiality_aware_relative_scoring',
    'weight_total',100,
    'weights',jsonb_build_object(
      'p50_days',10,'p90_days',10,'tco',18,'stability',10,'rci',6,'pci',6,
      'inspection_rate',4,'testing_rate',4,'inspection_days',4,'testing_days',4,
      'coldchain',8,'capacity',5,'schedule',4,'abnormal',7
    ),
    'materiality_thresholds',jsonb_build_object(
      'p50_days',0.25,'p90_days',0.5,'tco',500,'stability',2,'rci',0.3,'pci',0.3,
      'inspection_rate',1,'testing_rate',1,'inspection_days',0.25,'testing_days',0.25,
      'coldchain',0.3,'capacity',0.3,'schedule',0.5,'abnormal',0.3
    ),
    'evidence_scores',jsonb_build_object('A',100,'B',85,'C',65,'D',40),
    'freshness_days',jsonb_build_object('current',90,'acceptable',180,'stale',365),
    'required_scope',jsonb_build_array('cargo_group','fruit','country','origin_region','month','destination','data_scope','currency','container_type'),
    'scenarios',jsonb_build_array('normal_p50','peak_p90','regulatory_expected')
  ),
  now()
)
on conflict (code) do update
set label=excluded.label,status='active',active=true,config=excluded.config,
    activated_at=coalesce(public.route_model_versions.activated_at,excluded.activated_at);

create table if not exists public.route_chain_segments (
  id bigint generated by default as identity primary key,
  route_kind text not null check (route_kind in ('current','jiangmen')),
  route_id uuid not null,
  segment_order smallint not null check (segment_order between 1 and 9),
  segment_code text not null check (segment_code in (
    'origin_harvest','precool_pack','origin_inland','export_clearance','main_transport',
    'transshipment','import_port_ops','inspection_clearance','coldstorage_lastmile'
  )),
  segment_name text not null,
  origin_node text,
  destination_node text,
  p50_days numeric check (p50_days >= 0),
  p90_days numeric check (p90_days >= 0),
  cost_amount numeric check (cost_amount >= 0),
  currency text not null default 'CNY' check (currency ~ '^[A-Z]{3}$'),
  container_type text not null default '40RF',
  coldchain_risk_index numeric check (coldchain_risk_index between 0 and 10),
  evidence_level text check (evidence_level in ('A','B','C','D')),
  sample_size integer check (sample_size >= 0),
  public_source_text text,
  public_source_url text,
  source_updated_at timestamptz,
  notes text,
  is_demo boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint route_chain_segments_tail_check check (p50_days is null or p90_days is null or p90_days >= p50_days),
  constraint route_chain_segments_order_key unique (route_kind,route_id,segment_order),
  constraint route_chain_segments_code_key unique (route_kind,route_id,segment_code)
);

create index if not exists route_chain_segments_route_idx
  on public.route_chain_segments(route_kind,route_id,segment_order);

create table if not exists public.route_report_events (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.route_reports(id) on delete cascade,
  event_type text not null check (event_type in (
    'create','submit_review','approve_publish','return_draft','revoke','renew','rotate',
    'view','code_failed','migrated'
  )),
  actor_id uuid references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default now()
);

create index if not exists route_report_events_report_idx
  on public.route_report_events(report_id,created_at desc);
create index if not exists route_report_events_actor_idx
  on public.route_report_events(actor_id,created_at desc) where actor_id is not null;

create table if not exists public.route_report_visitors (
  report_id uuid not null references public.route_reports(id) on delete cascade,
  visitor_hash text not null check (length(visitor_hash) between 32 and 128),
  first_viewed_at timestamptz not null default now(),
  last_viewed_at timestamptz not null default now(),
  view_count bigint not null default 1 check (view_count >= 1),
  primary key (report_id,visitor_hash)
);

alter table public.route_report_views
  add column if not exists visitor_hash text;
create index if not exists route_report_views_visitor_idx
  on public.route_report_views(report_id,visitor_hash,viewed_at desc)
  where visitor_hash is not null;

alter table public.current_route_baselines
  add column if not exists is_demo boolean not null default false,
  add column if not exists currency text not null default 'CNY',
  add column if not exists container_type text not null default '40RF',
  add column if not exists cost_basis_date date,
  add column if not exists public_source_text text,
  add column if not exists public_source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid references public.profiles(id) on delete set null;

alter table public.jiangmen_routes
  add column if not exists is_demo boolean not null default false,
  add column if not exists currency text not null default 'CNY',
  add column if not exists container_type text not null default '40RF',
  add column if not exists cost_basis_date date,
  add column if not exists public_source_text text,
  add column if not exists public_source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid references public.profiles(id) on delete set null;

alter table public.sea_port_stats
  add column if not exists is_demo boolean not null default false,
  add column if not exists public_source_text text,
  add column if not exists public_source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid references public.profiles(id) on delete set null;
alter table public.land_port_stats
  add column if not exists is_demo boolean not null default false,
  add column if not exists public_source_text text,
  add column if not exists public_source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid references public.profiles(id) on delete set null;
alter table public.jiangmen_port_stats
  add column if not exists is_demo boolean not null default false,
  add column if not exists public_source_text text,
  add column if not exists public_source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid references public.profiles(id) on delete set null;

alter table public.current_route_baselines
  add constraint current_route_values_v2_check check (
    coalesce(p50_days,0)>=0 and coalesce(p90_days,0)>=0 and
    (p50_days is null or p90_days is null or p90_days>=p50_days) and
    coalesce(total_days,0)>=0 and coalesce(total_cost_per_container,0)>=0 and
    (stability_index is null or stability_index between 0 and 100) and
    (route_congestion_index is null or route_congestion_index between 0 and 10) and
    (coldchain_risk_index is null or coldchain_risk_index between 0 and 10) and
    (capacity_score is null or capacity_score between 0 and 10) and
    coalesce(schedule_frequency_per_week,0)>=0 and
    (abnormal_handling_score is null or abnormal_handling_score between 0 and 10)
  ),
  add constraint current_route_currency_v2_check check (currency ~ '^[A-Z]{3}$');

alter table public.jiangmen_routes
  add constraint jiangmen_route_values_v2_check check (
    coalesce(p50_days,0)>=0 and coalesce(p90_days,0)>=0 and
    (p50_days is null or p90_days is null or p90_days>=p50_days) and
    coalesce(total_days,0)>=0 and coalesce(total_cost_per_container,0)>=0 and
    (stability_index is null or stability_index between 0 and 100) and
    (route_congestion_index is null or route_congestion_index between 0 and 10) and
    (coldchain_risk_index is null or coldchain_risk_index between 0 and 10) and
    (capacity_score is null or capacity_score between 0 and 10) and
    coalesce(schedule_frequency_per_week,0)>=0 and
    (abnormal_handling_score is null or abnormal_handling_score between 0 and 10)
  ),
  add constraint jiangmen_route_currency_v2_check check (currency ~ '^[A-Z]{3}$'),
  add constraint jiangmen_route_month_v2_check check (month is null or month between 1 and 12);

alter table public.sea_port_stats add constraint sea_port_values_v2_check check (
  (inspection_rate is null or inspection_rate between 0 and 100) and
  (testing_rate is null or testing_rate between 0 and 100) and
  coalesce(inspection_days,0)>=0 and coalesce(testing_days,0)>=0 and
  (congestion_index is null or congestion_index between 0 and 10) and
  coalesce(p50_clearance_days,0)>=0 and coalesce(p90_clearance_days,0)>=0 and
  (p50_clearance_days is null or p90_clearance_days is null or p90_clearance_days>=p50_clearance_days) and
  coalesce(port_cost_per_container,0)>=0
);
alter table public.land_port_stats add constraint land_port_values_v2_check check (
  (inspection_rate is null or inspection_rate between 0 and 100) and
  (testing_rate is null or testing_rate between 0 and 100) and
  coalesce(inspection_days,0)>=0 and coalesce(testing_days,0)>=0 and
  (congestion_index is null or congestion_index between 0 and 10) and
  coalesce(p50_clearance_days,0)>=0 and coalesce(p90_clearance_days,0)>=0 and
  (p50_clearance_days is null or p90_clearance_days is null or p90_clearance_days>=p50_clearance_days) and
  coalesce(port_cost_per_container,0)>=0
);
alter table public.jiangmen_port_stats add constraint jiangmen_port_values_v2_check check (
  (inspection_rate is null or inspection_rate between 0 and 100) and
  (testing_rate is null or testing_rate between 0 and 100) and
  coalesce(inspection_days,0)>=0 and coalesce(testing_days,0)>=0 and
  (congestion_index is null or congestion_index between 0 and 10) and
  coalesce(p50_clearance_days,0)>=0 and coalesce(p90_clearance_days,0)>=0 and
  (p50_clearance_days is null or p90_clearance_days is null or p90_clearance_days>=p50_clearance_days) and
  coalesce(port_cost_per_container,0)>=0
);

create or replace function public.fonkon_record_route_report_view(
  p_report_id uuid,
  p_visitor_hash text,
  p_user_agent text default null,
  p_referrer text default null
) returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_inserted integer := 0;
begin
  insert into public.route_report_visitors(report_id,visitor_hash)
  values (p_report_id,left(p_visitor_hash,128))
  on conflict (report_id,visitor_hash) do nothing;
  get diagnostics v_inserted = row_count;

  if v_inserted = 0 then
    update public.route_report_visitors
    set last_viewed_at=now(), view_count=view_count+1
    where report_id=p_report_id and visitor_hash=left(p_visitor_hash,128);
  end if;

  insert into public.route_report_views(report_id,visitor_hash,user_agent,referrer)
  values (p_report_id,left(p_visitor_hash,128),left(p_user_agent,300),left(p_referrer,300));

  update public.route_reports
  set view_count=view_count+1,
      unique_view_count=unique_view_count+v_inserted,
      first_viewed_at=coalesce(first_viewed_at,now()),
      last_viewed_at=now(),
      updated_at=now()
  where id=p_report_id;
end;
$$;

create or replace function public.fonkon_route_report_code_attempt(
  p_report_id uuid,
  p_success boolean
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_failed integer;
  v_locked timestamptz;
begin
  select failed_code_attempts,locked_until into v_failed,v_locked
  from public.route_reports where id=p_report_id for update;

  if not found then return jsonb_build_object('ok',false,'not_found',true); end if;
  if v_locked is not null and v_locked>now() then
    return jsonb_build_object('ok',false,'locked',true,'locked_until',v_locked);
  end if;

  if p_success then
    update public.route_reports set failed_code_attempts=0,locked_until=null where id=p_report_id;
    return jsonb_build_object('ok',true,'locked',false);
  end if;

  v_failed:=coalesce(v_failed,0)+1;
  v_locked:=case when v_failed>=5 then now()+interval '15 minutes' else null end;
  update public.route_reports
  set failed_code_attempts=v_failed,locked_until=v_locked
  where id=p_report_id;
  insert into public.route_report_events(report_id,event_type,metadata)
  values (p_report_id,'code_failed',jsonb_build_object('attempt',v_failed,'locked_until',v_locked));
  return jsonb_build_object('ok',false,'locked',v_locked is not null,'locked_until',v_locked,'remaining',greatest(0,5-v_failed));
end;
$$;

alter table public.route_model_versions enable row level security;
alter table public.route_chain_segments enable row level security;
alter table public.route_report_events enable row level security;
alter table public.route_report_visitors enable row level security;

revoke all on table public.route_model_versions from anon,authenticated;
revoke all on table public.route_chain_segments from anon,authenticated;
revoke all on table public.route_report_events from anon,authenticated;
revoke all on table public.route_report_visitors from anon,authenticated;
revoke all on sequence public.route_chain_segments_id_seq from anon,authenticated;
revoke all on sequence public.route_report_events_id_seq from anon,authenticated;
revoke all on function public.fonkon_record_route_report_view(uuid,text,text,text) from public,anon,authenticated;
revoke all on function public.fonkon_route_report_code_attempt(uuid,boolean) from public,anon,authenticated;
grant execute on function public.fonkon_record_route_report_view(uuid,text,text,text) to service_role;
grant execute on function public.fonkon_route_report_code_attempt(uuid,boolean) to service_role;

update public.current_route_baselines
set is_demo=true,currency='CNY',container_type='40RF',cost_basis_date=date '2026-08-24',
    public_source_text='系统功能演示模拟数据（非真实运营数据）',source_updated_at=updated_at
where id in (
  'd1000000-0000-4000-8000-000000000001',
  'd1000000-0000-4000-8000-000000000002',
  'd1000000-0000-4000-8000-000000000003'
);
update public.jiangmen_routes
set is_demo=true,currency='CNY',container_type='40RF',cost_basis_date=date '2026-08-24',
    public_source_text='系统功能演示模拟数据（非真实运营数据）',source_updated_at=updated_at
where id='d2000000-0000-4000-8000-000000000001';
update public.sea_port_stats
set is_demo=true,public_source_text='系统功能演示模拟数据（非真实运营数据）',source_updated_at=updated_at
where id in (
  'd3000000-0000-4000-8000-000000000001',
  'd3000000-0000-4000-8000-000000000002',
  'd3000000-0000-4000-8000-000000000003'
);
update public.jiangmen_port_stats
set is_demo=true,public_source_text='系统功能演示模拟数据（非真实运营数据）',source_updated_at=updated_at
where id='d4000000-0000-4000-8000-000000000001';

insert into public.route_chain_segments(
  route_kind,route_id,segment_order,segment_code,segment_name,origin_node,destination_node,
  p50_days,p90_days,cost_amount,currency,container_type,coldchain_risk_index,evidence_level,
  sample_size,public_source_text,source_updated_at,is_demo
)
values
('current','d1000000-0000-4000-8000-000000000001',1,'origin_harvest','果园采收与集货','泰国东部果园','产地集货中心',0.4,0.6,2200,'CNY','40RF',2.0,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',2,'precool_pack','预冷、分级与装柜','产地集货中心','预冷包装场',0.3,0.5,3800,'CNY','40RF',2.2,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',3,'origin_inland','产地内陆运输','预冷包装场','林查班港',0.4,0.6,4200,'CNY','40RF',2.8,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',4,'export_clearance','出口报关与装船','林查班港堆场','林查班港船边',0.4,0.7,2300,'CNY','40RF',2.6,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',5,'main_transport','国际海运','林查班港','广州南沙港',5.4,6.8,28700,'CNY','40RF',4.0,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',6,'transshipment','直航（无中转）','海运主航段','广州南沙港',0,0,0,'CNY','40RF',1.0,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',7,'import_port_ops','进口港卸船与提柜','广州南沙港船边','南沙港冷链区',0.5,0.8,4200,'CNY','40RF',3.8,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',8,'inspection_clearance','查验、送检与通关','南沙港冷链区','南沙港闸口',0.7,1.0,4100,'CNY','40RF',4.4,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000001',9,'coldstorage_lastmile','冷库周转与末端配送','南沙港闸口','广州江南市场',0.7,0.8,7300,'CNY','40RF',3.2,'D',12,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),

('current','d1000000-0000-4000-8000-000000000002',1,'origin_harvest','果园采收与集货','泰国东部果园','产地集货中心',0.4,0.6,2200,'CNY','40RF',2.0,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',2,'precool_pack','预冷、分级与装柜','产地集货中心','预冷包装场',0.3,0.5,3800,'CNY','40RF',2.2,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',3,'origin_inland','产地内陆运输','预冷包装场','林查班港',0.4,0.6,4500,'CNY','40RF',2.8,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',4,'export_clearance','出口报关与装船','林查班港堆场','林查班港船边',0.4,0.7,2300,'CNY','40RF',2.6,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',5,'main_transport','国际海运','林查班港','深圳蛇口港',4.8,7.5,30200,'CNY','40RF',4.6,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',6,'transshipment','直航（无中转）','海运主航段','深圳蛇口港',0,0,0,'CNY','40RF',1.0,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',7,'import_port_ops','进口港卸船与提柜','深圳蛇口港船边','蛇口港冷链区',0.5,0.8,4600,'CNY','40RF',4.1,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',8,'inspection_clearance','查验、送检与通关','蛇口港冷链区','蛇口港闸口',0.7,1.0,4100,'CNY','40RF',4.8,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000002',9,'coldstorage_lastmile','冷库周转与末端配送','蛇口港闸口','广州江南市场',0.7,0.8,6900,'CNY','40RF',3.6,'D',10,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),

('current','d1000000-0000-4000-8000-000000000003',1,'origin_harvest','果园采收与集货','泰国东部果园','产地集货中心',0.4,0.6,2200,'CNY','40RF',2.0,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',2,'precool_pack','预冷、分级与装柜','产地集货中心','预冷包装场',0.3,0.5,3800,'CNY','40RF',2.2,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',3,'origin_inland','产地内陆运输','预冷包装场','林查班港',0.4,0.6,4600,'CNY','40RF',2.8,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',4,'export_clearance','出口报关与装船','林查班港堆场','林查班港船边',0.4,0.7,2300,'CNY','40RF',2.6,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',5,'main_transport','国际海运','林查班港','厦门港',5.6,6.9,26500,'CNY','40RF',3.7,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',6,'transshipment','直航（无中转）','海运主航段','厦门港',0,0,0,'CNY','40RF',1.0,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',7,'import_port_ops','进口港卸船与提柜','厦门港船边','厦门港冷链区',0.7,0.8,4300,'CNY','40RF',3.5,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',8,'inspection_clearance','查验、送检与通关','厦门港冷链区','厦门港闸口',0.8,1.0,3900,'CNY','40RF',4.0,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('current','d1000000-0000-4000-8000-000000000003',9,'coldstorage_lastmile','冷库周转与末端配送','厦门港闸口','广州江南市场',0.9,0.9,6600,'CNY','40RF',3.8,'D',9,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),

('jiangmen','d2000000-0000-4000-8000-000000000001',1,'origin_harvest','果园采收与集货','泰国东部果园','产地集货中心',0.4,0.5,2200,'CNY','40RF',1.8,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',2,'precool_pack','预冷、分级与装柜','产地集货中心','预冷包装场',0.3,0.4,3800,'CNY','40RF',2.0,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',3,'origin_inland','产地内陆运输','预冷包装场','林查班港',0.4,0.5,4300,'CNY','40RF',2.5,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',4,'export_clearance','出口报关与装船','林查班港堆场','林查班港船边',0.4,0.6,2300,'CNY','40RF',2.4,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',5,'main_transport','国际海运','林查班港','香港港',5.1,6.0,25400,'CNY','40RF',3.3,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',6,'transshipment','香港中转驳船','香港港','江门高新港',0.3,0.4,2100,'CNY','40RF',2.8,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',7,'import_port_ops','进口港卸船与提柜','江门高新港船边','江门港冷链区',0.4,0.5,3900,'CNY','40RF',2.2,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',8,'inspection_clearance','查验、送检与通关','江门港冷链区','江门港闸口',0.6,0.8,3400,'CNY','40RF',2.6,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true),
('jiangmen','d2000000-0000-4000-8000-000000000001',9,'coldstorage_lastmile','冷库周转与末端配送','江门港闸口','广州江南市场',0.6,0.8,5200,'CNY','40RF',2.4,'D',16,'系统功能演示模拟数据（非真实运营数据）','2026-08-24',true)
on conflict (route_kind,route_id,segment_order) do update set
  segment_code=excluded.segment_code,segment_name=excluded.segment_name,
  origin_node=excluded.origin_node,destination_node=excluded.destination_node,
  p50_days=excluded.p50_days,p90_days=excluded.p90_days,cost_amount=excluded.cost_amount,
  currency=excluded.currency,container_type=excluded.container_type,
  coldchain_risk_index=excluded.coldchain_risk_index,evidence_level=excluded.evidence_level,
  sample_size=excluded.sample_size,public_source_text=excluded.public_source_text,
  source_updated_at=excluded.source_updated_at,is_demo=true,updated_at=now();

update public.route_reports
set is_demo=true,
    model_version=coalesce(nullif(model_version,''),'FONKON-RM-1-LEGACY'),
    snapshot=jsonb_set(
      jsonb_set(snapshot,'{is_demo}','true'::jsonb,true),
      '{disclaimer}',
      to_jsonb('本报告使用系统模拟数据，仅用于功能演示与流程体验，不代表真实港口运营表现，不得作为对外报价或正式业务决策依据。'::text),
      true
    ),
    updated_at=now()
where snapshot::text like '%【演示】%' or snapshot::text like '%DEMO_ROUTE_REPORT%';

insert into public.route_report_events(report_id,event_type,metadata)
select id,'migrated',jsonb_build_object('migration','route_report_operating_v2')
from public.route_reports
where not exists (
  select 1 from public.route_report_events e
  where e.report_id=route_reports.id and e.event_type='migrated'
);

comment on table public.route_model_versions is 'Versioned deterministic route comparison model configuration';
comment on table public.route_chain_segments is 'Nine-stage full-chain time, cost, risk and source evidence by route';
comment on table public.route_report_events is 'Immutable report workflow and access-security audit events';
comment on table public.route_report_visitors is 'Hashed anonymous visitor counters without IP storage';
