create table if not exists public.route_reports (
  id uuid primary key default gen_random_uuid(),
  report_number text not null unique,
  title text not null,
  customer_id uuid references public.customers(id) on delete set null,
  opportunity_id uuid references public.opportunities(id) on delete set null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  status text not null default 'published' check (status in ('published','revoked','expired')),
  share_token text not null unique,
  access_code_hash text,
  expires_at timestamptz,
  snapshot jsonb not null,
  view_count bigint not null default 0 check (view_count >= 0),
  first_viewed_at timestamptz,
  last_viewed_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.route_report_views (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.route_reports(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  user_agent text,
  referrer text
);

create index if not exists route_reports_created_by_idx on public.route_reports(created_by, created_at desc);
create index if not exists route_reports_customer_idx on public.route_reports(customer_id, created_at desc);
create index if not exists route_reports_opportunity_idx on public.route_reports(opportunity_id);
create index if not exists route_reports_status_expiry_idx on public.route_reports(status, expires_at);
create index if not exists route_report_views_report_idx on public.route_report_views(report_id, viewed_at desc);

alter table public.route_reports enable row level security;
alter table public.route_report_views enable row level security;

revoke all on table public.route_reports from anon, authenticated;
revoke all on table public.route_report_views from anon, authenticated;
revoke all on sequence public.route_report_views_id_seq from anon, authenticated;

create or replace function public.fonkon_record_route_report_view(
  p_report_id uuid,
  p_user_agent text default null,
  p_referrer text default null
) returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.route_report_views(report_id, user_agent, referrer)
  values (p_report_id, left(p_user_agent, 300), left(p_referrer, 300));

  update public.route_reports
  set view_count = view_count + 1,
      first_viewed_at = coalesce(first_viewed_at, now()),
      last_viewed_at = now(),
      updated_at = now()
  where id = p_report_id;
end;
$$;

revoke all on function public.fonkon_record_route_report_view(uuid,text,text) from public, anon, authenticated;
grant execute on function public.fonkon_record_route_report_view(uuid,text,text) to service_role;

comment on table public.route_reports is 'Immutable client-facing FONKON route comparison report snapshots and share controls';
comment on table public.route_report_views is 'Privacy-minimized route report view events; no IP address is stored';
